[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "name"
requires-python = ">=3.12"
dynamic = ["version"]
readme = "README.MD"
dependencies = [
    "requests","pytest"
]

[project.optional-dependencies]

[project.entry-points]
